# Change these first
owner: be-brite # Your GitHub username
repo: britestatuspage # Your GitHub repository name

# Add your sites here
sites:
  - name: Home Page
    url: https://getbritehr.com/
    icon: https://app.be-brite.com/favicon.png
  - name: Admin Portal
    url: https://app.be-brite.com/
    icon: https://app.be-brite.com/favicon.png
  - name: Employee View
    url: https://britehr.app/hoolibenefits/1
    icon: https://app.be-brite.com/favicon.png
  - name: API
    url: https://api.be-brite.com/version
    icon: https://app.be-brite.com/favicon.png
  - name: Postgrest API
    url: https://api.be-brite.com/public/v1/bp/display_settings?id=eq.e2cf8f34-5301-4961-9bff-5f3d991066fc
    headers:
      - "BusinessID: e2cf8f34-5301-4961-9bff-5f3d991066fc"

assignees: # Users to assign downtime issues (optional)
  - troylelandshields
  - 4dex
  - tycrockett
  - ahackneyy

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.britebenefits.com
  icon: https://app.be-brite.com/favicon.png
  favicon: https://app.be-brite.com/favicon.png
  logoUrl: https://cdn.prod.website-files.com/687faf1501735ecaecd43546/687faf1501735ecaecd4357f_Brite-Black.png
  name: Brite Status page
  introTitle: "**Brite Benefits** monitor and status page"
  introMessage: "Below is a list of Brite Benefits resources and their current status"
  themeUrl: https://status.britebenefits.com/brite-theme.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: ""
