# Change these first
owner: be-brite # Your GitHub username
repo: britestatuspage # Your GitHub repository name

# Add your sites here
sites:
  - name: Home Page
    url: https://getbritehr.com/
    icon: https://app.be-brite.com/favicon.png
  - name: Admin Portal
    url: https://app.be-brite.com/
    icon: https://app.be-brite.com/favicon.png
  - name: Employee View
    url: https://britehr.app/hoolibenefits/1
    icon: https://app.be-brite.com/favicon.png
  - name: API
    url: https://api.be-brite.com/version
    icon: https://app.be-brite.com/favicon.png

assignees: # Users to assign downtime issues (optional)
  - troylelandshields

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.be-brite.com      
  baseUrl: /britestatuspage
  icon: https://app.be-brite.com/favicon.png
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://getbritehr.com/wp-content/uploads/2020/05/britehr-logo@2x.png
  name: Brite Status page
  introTitle: "**BriteHR** monitor and status page"
  introMessage: "Below is a list of BriteHR's resources and their current status"
  theme: https://be-brite.github.io/britestatuspage/themes/brite-theme.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
